CREATE TABLE stg_amazon_orders (
    user_id VARCHAR(100),
    product_id VARCHAR(100),
    category VARCHAR(100),
    subcategory VARCHAR(100),
    brand VARCHAR(100),
    price VARCHAR(50),
    discount VARCHAR(50),
    final_price VARCHAR(50),
    rating VARCHAR(50),
    review_count VARCHAR(50),
    stock VARCHAR(50),
    seller_id VARCHAR(100),
    seller_rating VARCHAR(50),
    purchase_date VARCHAR(50),
    shipping_time_days VARCHAR(50),
    location VARCHAR(100),
    device VARCHAR(50),
    payment_method VARCHAR(50),
    is_returned VARCHAR(20),
    delivery_status VARCHAR(50)
);